version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:11.2.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-minesweeper-{{ checksum "package.json" }}
            - v2-minesweeper-

      - run:
          command: "npm install"

      - save_cache:
          key: v2-minesweeper-{{ checksum "package.json" }}
          paths:
            - './node_modules'

  build:
    docker:
      - image: circleci/node:11.2.0

    steps:
      - checkout

      - attach_workspace:
          at: ./

      - restore_cache:
          keys:
            - v2-minesweeper-{{ checksum "package.json" }}
            - v2-minesweeper-

      - run:
          command: "npm run build"

      - store_artifacts:
          path: ./dist
          destination: build

      - persist_to_workspace:
          root: ./
          paths:
            - dist/*

  test:
    docker:
      - image: circleci/node:11.2.0

    steps:
      - checkout

      - attach_workspace:
          at: ./

      - restore_cache:
          keys:
            - v2-minesweeper-{{ checksum "package.json" }}
            - v2-minesweeper-

      - run:
          command: "npm run test"

  deploy:
    docker:
      - image: circleci/node:11.2.0

    steps:
      - checkout

      - attach_workspace:
          at: ./

      - run:
          command: "./script/deploy"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout

      - build:
          requires:
            - checkout

      - test:
          requires:
            - checkout

      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
