#!/bin/bash

# exit on first non-true return value
set -o errexit
# exit if a command in a pipeline fails
set -o pipefail

git config user.email "noah@batteredoats.com"
git config user.name "Noah H. Smith"

git checkout -b deploy
git add --all --force ./dist/
git commit --message "Deploying $CIRCLE_SHA1"
git push origin deploy:gh-pages --force
